final products = [
  {
    'id': "0",
    'title': "Men's Nike Shoes",
    'price': 900,
    'imageUrl': "assets/images/shoes1.jpg",
    'company': "Nike",
    'sizes': [5, 7, 9, 12],
  },
  {
    'id': "1",
    'title': "Men's Tiger Shoes",
    'price': 1000,
    'imageUrl': "assets/images/shoes2.png",
    'company': "Tiger",
    'sizes': [5, 7, 9, 12],
  },
  {
    'id': "2",
    'title': "Men's Bata Shoes",
    'price': 1100,
    'imageUrl': "assets/images/shoes3.jpg",
    'company': "Bata",
    'sizes': [5, 7, 9, 12],
  },
  {
    'id': "3",
    'title': "Men's Adidas Shoes",
    'price': 1200,
    'imageUrl': "assets/images/shoes4.jpg",
    'company': "Adidas",
    'sizes': [5, 7, 9, 12],
  },
  {
    'id': "4",
    'title': "Men's Nike Shoes",
    'price': 1300,
    'imageUrl': "assets/images/shoes5.png",
    'company': "Nike",
    'sizes': [5, 7, 9, 12],
  },
  {
    'id': "5",
    'title': "Men's Nike Shoes",
    'price': 1400,
    'imageUrl': "assets/images/shoes6.jpg",
    'company': "Nike",
    'sizes': [5, 7, 9, 12],
  },
  {
    'id': "6",
    'title': "Men's Nike Shoes",
    'price': 1500,
    'imageUrl': "assets/images/shoes7.jpg",
    'company': "Nike",
    'sizes': [5, 7, 9, 12],
  },
  {
    'id': "7",
    'title': "Men's Nike Shoes",
    'price': 1800,
    'imageUrl': "assets/images/shoes8.jpeg",
    'company': "Nike",
    'sizes': [5, 7, 9, 12],
  },
  {
    'id': "8",
    'title': "Men's Nike Shoes",
    'price': 1900,
    'imageUrl': "assets/images/shoes9.jpg",
    'company': "Nike",
    'sizes': [5, 7, 9, 12],
  },
  {
    'id': "9",
    'title': "Men's Nike Shoes",
    'price': 1800,
    'imageUrl': "assets/images/shoes10.jpg",
    'company': "Nike",
    'sizes': [5, 7, 9, 12],
  },
];

final cart = [
  {
    'id': "4",
    'title': "Men's Nike Shoes",
    'price': 1300,
    'imageUrl': "assets/images/shoes3.jpg",
    'company': "Nike",
    'size': 12,
  }
];
